# Generated by Django 4.2.16 on 2024-09-25 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0053_appsetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="mealplan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscriber", models.CharField(max_length=100)),
                (
                    "mealtime",
                    models.CharField(
                        choices=[("B", "breakfast"), ("L", "lunch"), ("D", "dinner")],
                        default="B",
                        max_length=1,
                    ),
                ),
                ("meal", models.CharField(max_length=100)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mealplans",
                        to="main.trainer",
                    ),
                ),
            ],
        ),
    ]
